version: '3.0'
services:
  postgres:
    build: db/
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  webapp:
    build: goapp/
    depends_on:
      - postgres
    ports:
     - "8080:8080"
    
volumes:
  postgres_data:

