apiVersion: apps/v1
kind: Deployment
metadata:
 name: webapp
 labels:
  app: webapp
spec:
 replicas: 3
 selector:
  matchLabels:
   app: webapp
 template:
 metadata:
  name: webapp
  labels:
   app: webapp
   type: webapp
 spec: 
  containers:
  - name: webapp
    image: snhpf9/webapp:latest
    imagePullPolicy: Always 
    ports:
    - containerPort: 8080
    envFrom:
     - secretRef:
        name: app-secret
  restartPolicy: Never
