apiVersion: v1
kind: Service
metadata:
 name: web-service
spec:
 type: NodePort
 ports: 
  - targetPort: 8080
    port: 8080
    nodePort: 30008
    protocol: TCP
 selector:
  app: webapp
  type: webapp

